export const BANKS = [
  {
    bankName: "경남은행",
    financialCode: "039",
    code: "39",
    koreanName: "경남",
    englishName: "KYONGNAMBANK",
  },
  {
    bankName: "광주은행",
    financialCode: "034",
    code: "34",
    koreanName: "광주",
    englishName: "GWANGJUBANK",
  },
  {
    bankName: "단위농협(지역농축협)",
    financialCode: "012",
    code: "12",
    koreanName: "단위농협",
    englishName: "LOCALNONGHYEOP",
  },
  {
    bankName: "부산은행",
    financialCode: "032",
    code: "32",
    koreanName: "부산",
    englishName: "BUSANBANK",
  },
  {
    bankName: "새마을금고",
    financialCode: "045",
    code: "45",
    koreanName: "새마을",
    englishName: "SAEMAUL",
  },
  {
    bankName: "산림조합",
    financialCode: "064",
    code: "64",
    koreanName: "산림",
    englishName: "SANLIM",
  },
  {
    bankName: "신한은행",
    financialCode: "088",
    code: "88",
    koreanName: "신한",
    englishName: "SHINHAN",
  },
  {
    bankName: "신협",
    financialCode: "048",
    code: "48",
    koreanName: "신협",
    englishName: "SHINHYEOP",
  },
  {
    bankName: "씨티은행",
    financialCode: "027",
    code: "27",
    koreanName: "씨티",
    englishName: "CITI",
  },
  {
    bankName: "우리은행",
    financialCode: "020",
    code: "20",
    koreanName: "우리",
    englishName: "WOORI",
  },
  {
    bankName: "우체국예금보험",
    financialCode: "071",
    code: "71",
    koreanName: "우체국",
    englishName: "POST",
  },
  {
    bankName: "저축은행중앙회",
    financialCode: "050",
    code: "50",
    koreanName: "저축",
    englishName: "SAVINGBANK",
  },
  {
    bankName: "전북은행",
    financialCode: "037",
    code: "37",
    koreanName: "전북",
    englishName: "JEONBUKBANK",
  },
  {
    bankName: "제주은행",
    financialCode: "035",
    code: "35",
    koreanName: "제주",
    englishName: "JEJUBANK",
  },
  {
    bankName: "카카오뱅크",
    financialCode: "090",
    code: "90",
    koreanName: "카카오",
    englishName: "KAKAOBANK",
  },
  {
    bankName: "케이뱅크",
    financialCode: "089",
    code: "89",
    koreanName: "케이",
    englishName: "KBANK",
  },
  {
    bankName: "토스뱅크",
    financialCode: "092",
    code: "92",
    koreanName: "토스",
    englishName: "TOSSBANK",
  },
  {
    bankName: "하나은행",
    financialCode: "081",
    code: "81",
    koreanName: "하나",
    englishName: "HANA",
  },
  {
    bankName: "홍콩상하이은행",
    financialCode: "054",
    code: "54",
    koreanName: "-",
    englishName: "HSBC",
  },
  {
    bankName: "IBK기업은행",
    financialCode: "003",
    code: "03",
    koreanName: "기업",
    englishName: "IBK",
  },
  {
    bankName: "KB국민은행",
    financialCode: "004",
    code: "06",
    koreanName: "국민",
    englishName: "KOOKMIN",
  },
  {
    bankName: "DGB대구은행",
    financialCode: "031",
    code: "31",
    koreanName: "대구",
    englishName: "DAEGUBANK",
  },
  {
    bankName: "KDB산업은행",
    financialCode: "002",
    code: "02",
    koreanName: "산업",
    englishName: "KDBBANK",
  },
  {
    bankName: "NH농협은행",
    financialCode: "011",
    code: "11",
    koreanName: "농협",
    englishName: "NONGHYEOP",
  },
  {
    bankName: "SC제일은행",
    financialCode: "023",
    code: "23",
    koreanName: "SC제일",
    englishName: "SC",
  },
  {
    bankName: "Sh수협은행",
    financialCode: "007",
    code: "07",
    koreanName: "수협",
    englishName: "SUHYEOP",
  },
];
