export const CARD_COMPANIES = [
  {
    company: "기업 BC",
    code: "3K",
    koreanName: "기업비씨",
    englishName: "IBK_BC",
  },
  {
    company: "광주은행",
    code: "46",
    koreanName: "광주",
    englishName: "GWANGJUBANK",
  },
  { company: "롯데카드", code: "71", koreanName: "롯데", englishName: "LOTTE" },
  {
    company: "KDB산업은행",
    code: "30",
    koreanName: "산업",
    englishName: "KDBBANK",
  },
  { company: "BC카드", code: "31", koreanName: "-", englishName: "BC" },
  {
    company: "삼성카드",
    code: "51",
    koreanName: "삼성",
    englishName: "SAMSUNG",
  },
  {
    company: "새마을금고",
    code: "38",
    koreanName: "새마을",
    englishName: "SAEMAUL",
  },
  {
    company: "신한카드",
    code: "41",
    koreanName: "신한",
    englishName: "SHINHAN",
  },
  { company: "신협", code: "62", koreanName: "신협", englishName: "SHINHYEOP" },
  { company: "씨티카드", code: "36", koreanName: "씨티", englishName: "CITI" },
  {
    company: "우리BC카드(BC 매입)",
    code: "33",
    koreanName: "우리",
    englishName: "WOORI",
  },
  {
    company: "우리카드(우리 매입)",
    code: "W1",
    koreanName: "우리",
    englishName: "WOORI",
  },
  {
    company: "우체국예금보험",
    code: "37",
    koreanName: "우체국",
    englishName: "POST",
  },
  {
    company: "저축은행중앙회",
    code: "39",
    koreanName: "저축",
    englishName: "SAVINGBANK",
  },
  {
    company: "전북은행",
    code: "35",
    koreanName: "전북",
    englishName: "JEONBUKBANK",
  },
  {
    company: "제주은행",
    code: "42",
    koreanName: "제주",
    englishName: "JEJUBANK",
  },
  {
    company: "카카오뱅크",
    code: "15",
    koreanName: "카카오뱅크",
    englishName: "KAKAOBANK",
  },
  {
    company: "케이뱅크",
    code: "3A",
    koreanName: "케이뱅크",
    englishName: "KBANK",
  },
  {
    company: "토스뱅크",
    code: "24",
    koreanName: "토스뱅크",
    englishName: "TOSSBANK",
  },
  { company: "하나카드", code: "21", koreanName: "하나", englishName: "HANA" },
  {
    company: "현대카드",
    code: "61",
    koreanName: "현대",
    englishName: "HYUNDAI",
  },
  {
    company: "KB국민카드",
    code: "11",
    koreanName: "국민",
    englishName: "KOOKMIN",
  },
  {
    company: "NH농협카드",
    code: "91",
    koreanName: "농협",
    englishName: "NONGHYEOP",
  },
  {
    company: "Sh수협은행",
    code: "34",
    koreanName: "수협",
    englishName: "SUHYEOP",
  },
  { company: "페이코", code: "-", koreanName: "-", englishName: "PCP" },
  { company: "KB증권", code: "-", koreanName: "-", englishName: "KBS" },
];
